{"name": "test_get[djkfhdsjfdss]", "status": "broken", "statusDetails": {"message": "AttributeError: 'Department' object has no attribute 'code'", "trace": "self = <api.department.Department object at 0x0000023E3A5E0278>\npath = '$..userid'\nr = {'department': [], 'errcode': 60111, 'errmsg': 'userid not found, hint: [1634968225_148_c41e34e72fcb020c38cb4e228b224f... ip: 120.244.40.105, more info at https://open.work.weixin.qq.com/devtool/query?e=60111', 'is_leader_in_dept': [], ...}\nkwargs = {'assertion': 'djkfhdsjfdss'}\n\n    def jsonpath(self, path, r=None, **kwargs):\n        if r is None:\n            r = self.r.json()\n        try:\n>           return jsonpath(r, path)[0]\nE           TypeError: 'bool' object is not subscriptable\n\n..\\api\\baseapi.py:26: TypeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testcase.test_department.TestDepartment object at 0x0000023E3B2752E8>\nuserid = 'djkfhdsjfdss'\n\n    @allure.step('测试')\n    @pytest.mark.parametrize('userid',['dfmfdsdfdddfsffddf','djkfhdsjfdss'])\n    def test_get(self,userid):\n        self.department.params['userid'] =userid\n>       self.department.api_steps(self.data)\n\ntest_department.py:16: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\api\\baseapi.py:66: in api_steps\n    self.code = getattr(self, 'jsonpath')(**step)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <api.department.Department object at 0x0000023E3A5E0278>\npath = '$..userid'\nr = {'department': [], 'errcode': 60111, 'errmsg': 'userid not found, hint: [1634968225_148_c41e34e72fcb020c38cb4e228b224f... ip: 120.244.40.105, more info at https://open.work.weixin.qq.com/devtool/query?e=60111', 'is_leader_in_dept': [], ...}\nkwargs = {'assertion': 'djkfhdsjfdss'}\n\n    def jsonpath(self, path, r=None, **kwargs):\n        if r is None:\n            r = self.r.json()\n        try:\n            return jsonpath(r, path)[0]\n        except :\n>           Get_log().log_error(self.code)\nE           AttributeError: 'Department' object has no attribute 'code'\n\n..\\api\\baseapi.py:28: AttributeError"}, "steps": [{"name": "测试", "status": "broken", "statusDetails": {"message": "AttributeError: 'Department' object has no attribute 'code'\n", "trace": "  File \"D:\\python\\lib\\site-packages\\allure_commons\\_allure.py\", line 172, in impl\n    return func(*a, **kw)\n  File \"H:\\练习\\test_reques_wework\\testcase\\test_department.py\", line 16, in test_get\n    self.department.api_steps(self.data)\n  File \"H:\\练习\\test_reques_wework\\api\\baseapi.py\", line 66, in api_steps\n    self.code = getattr(self, 'jsonpath')(**step)\n  File \"H:\\练习\\test_reques_wework\\api\\baseapi.py\", line 28, in jsonpath\n    Get_log().log_error(self.code)\n"}, "attachments": [{"source": "f22eae51-d8ec-43ed-8e83-02ccb0d8e495-attachment.attach"}], "parameters": [{"name": "userid", "value": "'djkfhdsjfdss'"}], "start": 1634412503009, "stop": 1634412503681}], "attachments": [{"name": "log", "source": "75bd12d0-33a6-4116-8c5f-9cd65c8fc3d9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "userid", "value": "'djkfhdsjfdss'"}], "start": 1634412503009, "stop": 1634412503681, "uuid": "be81e314-9b3d-41d0-8630-cadb008cbd8f", "historyId": "5c3bc40267495b9ef4867fee7c6d02db", "testCaseId": "dcccf3236d29225883a842a7b88face6", "fullName": "testcase.test_department.TestDepartment#test_get", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_department"}, {"name": "subSuite", "value": "TestDepartment"}, {"name": "host", "value": "PC-202008151337"}, {"name": "thread", "value": "5136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_department"}]}